language: ruby
rvm:
- 2.0.0
- 2.1.0
script:
- rake spec
- ./cli-test.sh
deploy:
  provider: rubygems
  api_key:
    secure: iLK75fek/gb6iDaEzOB44npnoWdiOwjiM/kx1xKGVOVGwyRGbLo0doZh+wnDz2GBdvzJTlaWmHDtCovhCTShNsbTlvRBf9gNg1TwDQmed5NqokEpSPESiCaJSTwTYYCafpRVgEXxtYDb/O6rfsLKptfKsc6OKdRJNKwzblsgzlI=
  on:
    repo: cybertk/git-copy
    tags: true
