language: ruby
rvm:
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: iLK75fek/gb6iDaEzOB44npnoWdiOwjiM/kx1xKGVOVGwyRGbLo0doZh+wnDz2GBdvzJTlaWmHDtCovhCTShNsbTlvRBf9gNg1TwDQmed5NqokEpSPESiCaJSTwTYYCafpRVgEXxtYDb/O6rfsLKptfKsc6OKdRJNKwzblsgzlI=
  gem: git-copy
  on:
    repo: cybertk/git-copy
    branch: release
